C:\VulkanSDK\1.3.231.1\Bin\glslc.exe SimpleShader.vert -o ../Shaders/SimpleShader.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe SimpleShader.frag -o ../Shaders/SimpleShader.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Test.vert -o ../Shaders/Test.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Test.frag -o ../Shaders/Test.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe EnvMap.vert -o ../Shaders/EnvMap.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe EnvMap.frag -o ../Shaders/EnvMap.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Lighting.vert -o ../Shaders/Lighting.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Lighting.frag -o ../Shaders/Lighting.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Sphere.vert -o ../Shaders/Sphere.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Sphere.frag -o ../Shaders/Sphere.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Skybox.vert -o ../Shaders/Skybox.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Skybox.frag -o ../Shaders/Skybox.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Test2.vert -o ../Shaders/Test2.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Test2.frag -o ../Shaders/Test2.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Skybox2.vert -o ../Shaders/Skybox2.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Skybox2.frag -o ../Shaders/Skybox2.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe GLTF.vert -o ../Shaders/GLTF.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe GLTF.frag -o ../Shaders/GLTF.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Deferred\GeometryPass.vert -o ../Shaders/GeometryPass.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Deferred\GeometryPass.frag -o ../Shaders/GeometryPass.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Deferred\LightingPass.vert -o ../Shaders/LightingPass.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Deferred\LightingPass.frag -o ../Shaders/LightingPass.frag.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Deferred\LightingPassLight.vert -o ../Shaders/LightingPassLight.vert.spv
C:\VulkanSDK\1.3.231.1\Bin\glslc.exe Deferred\LightingPassLight.frag -o ../Shaders/LightingPassLight.frag.spv
pause